-- phpMyAdmin SQL Dump
-- version 3.5.8.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 23, 2020 at 09:12 AM
-- Server version: 5.6.34
-- PHP Version: 5.5.38

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `webdemo_db`
--

-- --------------------------------------------------------

--
-- Table structure for table `detail`
--

CREATE TABLE IF NOT EXISTS `detail` (
  `detailid` int(10) NOT NULL AUTO_INCREMENT,
  `detail_name` varchar(255) NOT NULL,
  `detail_intro` varchar(255) NOT NULL,
  `SEO_keywords` varchar(255) NOT NULL,
  `SEO_description` varchar(255) NOT NULL,
  `detail_feature` varchar(255) NOT NULL,
  `detail_img` varchar(255) NOT NULL,
  `detail_content` longtext NOT NULL,
  `detail_date` int(50) NOT NULL,
  `status` char(1) NOT NULL,
  `userid` int(10) NOT NULL,
  `cateid` int(10) NOT NULL,
  `labelid` int(10) NOT NULL,
  PRIMARY KEY (`detailid`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=41 ;

--
-- Dumping data for table `detail`
--

INSERT INTO `detail` (`detailid`, `detail_name`, `detail_intro`, `SEO_keywords`, `SEO_description`, `detail_feature`, `detail_img`, `detail_content`, `detail_date`, `status`, `userid`, `cateid`, `labelid`) VALUES
(3, 'Web doanh nghiep 01', 'Web doanh nghiep 01', 'Web doanh nghiep 01', 'Web doanh nghiep 01', '', '', 'Web doanh nghiep 01', 0, 'Y', 1, 3, 1),
(4, 'Web doanh nghiep 02', 'Web doanh nghiep 02', '                                                                        Web doanh nghiep 02                                                                        ', '                                                                        Web doanh nghiep 02                                                                        ', '', '1587202342_sample-detail.jpg', 'Web doanh nghiep 02', 0, 'Y', 2, 3, 5),
(19, 'Kapee', 'Ws-Kapee', 'Thiết Kế Website Thời Trang', 'Chuyên thiết kế Website Thời Trang trên Toàn Quốc.\r\nWebsite với nhiều chức năng bán hàng trong ngành thời trang, được nhiều cửa hàng tin dùng và chọn lựa để kinh doanh Online Thời Trang                                    ', '1587224197_kapee.presslayouts_avatar.jpg', '1587224197_kapee.presslayouts_resize.jpg', '<p>Kapee là được thiết kế với trên tiêu chí nhanh, sạch, tùy biến cao và phù hợp cho tất cả các loại cửa hàng như Thời trang, Điện tử, Nội thất, Phụ kiện,... Giao diện này đi kèm với rất nhiều tính năng và biến thể: Responsive Layout, Mega Menu, Page Builder, Slider, Product Quick View, Search,...</p>', 1587224197, 'Y', 11, 2, 6),
(21, 'Boyka', 'Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da', 'Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da', 'Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da. Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn.     ', '1587544434_3-avatar.jpg', '1587544434_3.jpg', '<p>Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da. Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho cửa hàng trực tuyến của bạn.</p>', 1587544434, 'Y', 2, 2, 6),
(22, 'Boyka #2', ' Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn', ' Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn', 'Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho cửa hàng trực tuyến của bạn.', '1587546238_4-avatar.jpg', '1587546238_4.jpg', '<p><span style="font-family:montserrat; font-size:14px">Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da. Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho cửa hàng trực tuyến của bạn.</span></p>', 1587546238, 'Y', 2, 2, 6),
(23, 'Boyka #3', 'Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da', 'Web bán hàng thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến', 'Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân', '1587546689_5-vatar.jpg', '1587546689_5.jpg', '<p><span style="font-family:montserrat; font-size:14px">Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da. Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho cửa hàng trực tuyến của bạn.</span></p>', 1587546689, 'Y', 2, 2, 6),
(24, 'Boyka #4', 'Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da', 'Web bán hàng thời trang Boyka', 'Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho ', '1587546801_6-avatar.jpg', '1587546801_6.jpg', '<p><span style="font-family:montserrat; font-size:14px">Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da. Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho cửa hàng trực tuyến của bạn.</span></p>', 1587546801, 'Y', 2, 2, 6),
(25, 'Boyka #5', 'Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da', 'Web bán hàng thời trang giầy dép Boyka', 'Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho ', '1587546954_7-avtar.jpg', '1587546954_7.jpg', '<p><span style="font-family:montserrat; font-size:14px">Boyka - Mẫu thương mại điện tử thời trang đơn giản và đáp ứng cho cửa hàng thời trang trực tuyến, chủ yếu tập trung vào giày dép và hàng da. Boyka được thiết kế thanh lịch, đảm bảo một không gian trực tuyến tuyệt vời để hiển thị các sản phẩm của bạn. Nếu bạn muốn tạo bất kỳ cửa hàng thương mại điện tử, trang web kinh doanh, blog hoặc danh mục đầu tư cá nhân, Boyka luôn là lựa chọn phù hợp cho cửa hàng trực tuyến của bạn.</span></p>', 1587546954, 'Y', 2, 2, 7),
(26, 'Boyka #6', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', 'Web bán hàng thời trang DorNo', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', '1587547908_8-avatar.jpg', '1587547908_8.jpg', '<p>Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.</p>', 1587547908, 'Y', 2, 2, 6),
(27, 'DORNO #2', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', 'Web Bán Hàng Thời Trang DorNo', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', '1587548218_9-avatar.jpg', '1587548218_9.jpg', '<p><span style="font-family:montserrat; font-size:14px">Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.</span></p>', 1587548218, 'Y', 2, 2, 8),
(28, 'DORNO #3', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', 'Web Bán Hàng Trang Sức DorNo', 'Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', '1587626232_10-avatar.jpg', '1587626232_10.jpg', '<p><span style="font-family:montserrat; font-size:14px">Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.</span></p>', 1587626232, 'Y', 2, 2, 9),
(29, 'DORNO #4', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', 'Web Bán Hàng Thời Trang DORNO #4', 'Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.', '1587626293_11-avatar.jpg', '1587626293_11.jpg', '<p><span style="font-family:montserrat; font-size:14px">Dorno - Web bán hàng Thương mại điện tử Thời trang chủ yếu tập trung vào giày dép và đồ da. Trang web này hoàn toàn đáp ứng cho tất cả các loại thiết bị. Ngoài ra, trang web đẹp và độc đáo này chắc chắn sẽ thu hút khách truy cập.</span></p>', 1587626293, 'Y', 2, 2, 6),
(31, 'ELIZA #1', 'Eliza - Mẫu website thời trang nhanh và thân thiện với người dùng cho cửa hàng điện tử của bạn. Đáp ứng và hoạt động hoàn hảo trên tất cả các thiết bị. Thiết kế sáng tạo dễ sử dụng cho những người dùng không rành về công nghệ.', 'Web Bán Hàng Túi Xách Eliza', 'Eliza - Mẫu website thời trang nhanh và thân thiện với người dùng cho cửa hàng điện tử của bạn. Đáp ứng và hoạt động hoàn hảo trên tất cả các thiết bị. Thiết kế sáng tạo dễ sử dụng cho những người dùng không rành về công nghệ.', '1587627104_12-avtar.jpg', '1587627104_12.jpg', '<p>Eliza - Mẫu website thời trang nhanh và thân thiện với người dùng cho cửa hàng điện tử của bạn. Đáp ứng và hoạt động hoàn hảo trên tất cả các thiết bị. Thiết kế sáng tạo dễ sử dụng cho những người dùng không rành về công nghệ.</p>', 1587627104, 'Y', 2, 2, 10),
(32, 'OLSON #1', 'Olson - Mẫu Web thời trang tuyệt vời để xây dựng trang web thương mại điện tử của bất kỳ loại hình kinh doanh nào. Bạn có thể bán Sản phẩm thời trang, Thời trang nam, Thời trang nữ, Sản phẩm trẻ em, Sản phẩm may sẵn, Giày, Kính râm, Đồng hồ, Mỹ phẩm, Điện', 'Web Bán Hàng Thời Trang OLSON #1', 'Olson - Mẫu Web thời trang tuyệt vời để xây dựng trang web thương mại điện tử của bất kỳ loại hình kinh doanh nào. Bạn có thể bán Sản phẩm thời trang, Thời trang nam, Thời trang nữ, Sản phẩm trẻ em, Sản phẩm may sẵn, Giày, Kính râm, Đồng hồ, Mỹ phẩm, Điện', '1587627959_13-avatar.jpg', '1587627959_13.jpg', '<p>Olson - Mẫu Web thời trang tuyệt vời để xây dựng trang web thương mại điện tử của bất kỳ loại hình kinh doanh nào. Bạn có thể bán Sản phẩm thời trang, Thời trang nam, Thời trang nữ, Sản phẩm trẻ em, Sản phẩm may sẵn, Giày, Kính râm, Đồng hồ, Mỹ phẩm, Điện tử, Tiện ích, Nội thất và tất cả các sản phẩm của nhà cung cấp khác sử dụng mẫu Olson HTML.</p>\r\n\r\n<p>Ngoài ra, Olson là một mẫu đáp ứng 100%. phù hợp với tất cả các loại thiết bị. Tất cả các khía cạnh cần thiết để đối phó với ngành Thương mại điện tử đều có sẵn trong mẫu này. Thiết kế và trang phục của mẫu này là hoàn toàn độc đáo và sáng tạo. Sử dụng mẫu được tối ưu hóa SEO này để thu hút khách truy cập tiềm năng và cung cấp cho họ những sản phẩm chất lượng. Nó sẽ làm và không thể ngăn cản được ’bạn.</p>', 1587627959, 'Y', 2, 2, 6),
(33, 'OLSON #2', 'Olson - Mẫu Web thời trang tuyệt vời để xây dựng trang web thương mại điện tử của bất kỳ loại hình kinh doanh nào. Bạn có thể bán Sản phẩm thời trang, Thời trang nam, Thời trang nữ, Sản phẩm trẻ em, Sản phẩm may sẵn, Giày, Kính râm, Đồng hồ, Mỹ phẩm, Điện', 'Web Bán Hàng Thời Trang OLSON #1', 'Olson - Mẫu Web thời trang tuyệt vời để xây dựng trang web thương mại điện tử của bất kỳ loại hình kinh doanh nào. Bạn có thể bán Sản phẩm thời trang, Thời trang nam, Thời trang nữ, Sản phẩm trẻ em, Sản phẩm may sẵn, Giày, Kính râm, Đồng hồ, Mỹ phẩm, Điện', '1587628057_14-avatar.jpg', '1587628057_14.jpg', '<p><span style="font-family:montserrat; font-size:14px">Olson - Mẫu Web thời trang tuyệt vời để xây dựng trang web thương mại điện tử của bất kỳ loại hình kinh doanh nào. Bạn có thể bán Sản phẩm thời trang, Thời trang nam, Thời trang nữ, Sản phẩm trẻ em, Sản phẩm may sẵn, Giày, Kính râm, Đồng hồ, Mỹ phẩm, Điện tử, Tiện ích, Nội thất, ...</span></p>', 1587628057, 'Y', 2, 2, 6),
(34, 'REID #1', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', 'Web Bán Hàng Thời Trang REID #1', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', '1587628456_15-avatar.jpg', '1587628456_15.jpg', '<p>Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Giày, Kính râm, Thời trang mùa đông, Phụ kiện du lịch, Máy ảnh, Sản phẩm điện, Đồng hồ đeo tay và hầu hết tất cả các sản phẩm bán lẻ khác.</p>', 1587628456, 'Y', 2, 2, 6),
(35, 'REID #2', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', 'Web Bán Hàng Thời Trang REID #2', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', '1587629845_16-avatar.jpg', '1587629845_16.jpg', '<p><span style="font-family:montserrat; font-size:14px">Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Giày, Kính râm, Thời trang mùa đông, Phụ kiện du lịch, Máy ảnh, Sản phẩm điện, Đồng hồ đeo tay và hầu hết tất cả các sản phẩm bán lẻ khác.</span></p>', 1587629845, 'Y', 2, 2, 7),
(36, 'REID #3', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', 'Web Bán Hàng Thời Trang REID #3', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', '1587632216_17-avatar.jpg', '1587632216_17.jpg', '<p><span style="font-family:montserrat; font-size:14px">Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Giày, Kính râm, Thời trang mùa đông, Phụ kiện du lịch, Máy ảnh, Sản phẩm điện, Đồng hồ đeo tay và hầu hết tất cả các sản phẩm bán lẻ khác.</span></p>', 1587632216, 'Y', 2, 2, 6),
(37, 'REID #4', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', 'Web Bán Hàng Thời Trang REID #4', 'Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Gi', '1587632259_18-avatar.jpg', '1587632259_18.jpg', '<p><span style="font-family:montserrat; font-size:14px">Reid - Mẫu Web thương mại điện tử thời trang sáng tạo đáng kinh ngạc để làm cho các trang web bán sản phẩm thời trang trực tuyến. Reid là một mẫu trang web sáng tạo mà bạn có thể sử dụng để bán thời trang trẻ em, Thời trang nam, Thời trang nữ, May sẵn, Giày, Kính râm, Thời trang mùa đông, Phụ kiện du lịch, Máy ảnh, Sản phẩm điện, Đồng hồ đeo tay và hầu hết tất cả các sản phẩm bán lẻ khác.</span></p>', 1587632259, 'Y', 2, 2, 6),
(38, 'EMPIRE', 'Empire - Mẫu web thương mại điện tử tối giản là một thiết kế thanh lịch và sạch sẽ - thích hợp để bán quần áo, thời trang, thời trang cao cấp, thời trang nam, thời trang nữ, phụ kiện, kỹ thuật số, trẻ em, đồng hồ, trang sức, giày dép, trẻ em, đồ nội thất,', 'Web Bán Hàng Thời Trang EMPIRE', 'Empire - Mẫu web thương mại điện tử tối giản là một thiết kế thanh lịch và sạch sẽ - thích hợp để bán quần áo, thời trang, thời trang cao cấp, thời trang nam, thời trang nữ, phụ kiện, kỹ thuật số, trẻ em, đồng hồ, trang sức, giày dép, trẻ em, đồ nội thất,', '1587632365_19-avatar.jpg', '1587632365_19.jpg', '<p>Empire - Mẫu web thương mại điện tử tối giản là một thiết kế thanh lịch và sạch sẽ - thích hợp để bán quần áo, thời trang, thời trang cao cấp, thời trang nam, thời trang nữ, phụ kiện, kỹ thuật số, trẻ em, đồng hồ, trang sức, giày dép, trẻ em, đồ nội thất, thể thao, vv .. Nó có chiều rộng đáp ứng đầy đủ tự động điều chỉnh theo bất kỳ kích thước hoặc độ phân giải màn hình nào.</p>', 1587632365, 'Y', 2, 2, 6),
(39, 'EMPIRE #2', 'Empire - Mẫu web thương mại điện tử tối giản là một thiết kế thanh lịch và sạch sẽ - thích hợp để bán quần áo, thời trang, thời trang cao cấp, thời trang nam, thời trang nữ, phụ kiện, kỹ thuật số, trẻ em, đồng hồ, trang sức, giày dép, trẻ em, đồ nội thất,', 'Web Bán Hàng Thời Trang EMPIRE #2', 'Empire - Mẫu web thương mại điện tử tối giản là một thiết kế thanh lịch và sạch sẽ - thích hợp để bán quần áo, thời trang, thời trang cao cấp, thời trang nam, thời trang nữ, phụ kiện, kỹ thuật số, trẻ em, đồng hồ, trang sức, giày dép, trẻ em, đồ nội thất,', '1587632415_20-avatar.jpg', '1587632415_20.jpg', '<p><span style="font-family:montserrat; font-size:14px">Empire - Mẫu web thương mại điện tử tối giản là một thiết kế thanh lịch và sạch sẽ - thích hợp để bán quần áo, thời trang, thời trang cao cấp, thời trang nam, thời trang nữ, phụ kiện, kỹ thuật số, trẻ em, đồng hồ, trang sức, giày dép, trẻ em, đồ nội thất, thể thao, vv .. Nó có chiều rộng đáp ứng đầy đủ tự động điều chỉnh theo bất kỳ kích thước hoặc độ phân giải màn hình nào.</span></p>', 1587632415, 'Y', 2, 2, 6),
(40, 'BOUTIQUE #1', 'Mẫu giao diện web bán hàng thời trang sáng tạo thân thiện người dùng và tương thích với tất cả các thiết bị di động và máy tính. Bạn có thể sử dụng với nhiều lĩnh vực Thời Trang khác nhau : Quần Áo Nam, Quần Áo Nữ, Trang Sức, Giầy Dép, Túi Xách ,.... ', 'Web Bán Hàng Thời Trang BOUTIQUE #1', 'Mẫu giao diện web bán hàng thời trang sáng tạo thân thiện người dùng và tương thích với tất cả các thiết bị di động và máy tính. Bạn có thể sử dụng với nhiều lĩnh vực Thời Trang khác nhau : Quần Áo Nam, Quần Áo Nữ, Trang Sức, Giầy Dép, Túi Xách ,.... ', '1587632644_21-avatar.jpg', '1587632644_21.jpg', '<p>Mẫu giao diện web bán hàng thời trang sáng tạo thân thiện người dùng và tương thích với tất cả các thiết bị di động và máy tính. Bạn có thể sử dụng với nhiều lĩnh vực Thời Trang khác nhau : Quần Áo Nam, Quần Áo Nữ, Trang Sức, Giầy Dép, Túi Xách ,.... </p>', 1587632644, 'Y', 2, 2, 6);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
